remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Flomingl Documentation
description: Privacy Policy and Terms of Service for Flomingl
show_downloads: false

github:
  is_project_page: false 